### ISSUE TITLE
Warning: The result of getSnapshot should be cached to avoid an infinite loop

### ISSUE THREAD

**Issue by QiYan93** [Connect2IC/connect2ic#11]
When use [useConnect]  

![image](https://user-images.githubusercontent.com/17244631/171182799-9336333b-97e2-41ce-b9a9-e5e82ec09678.png)

**Comment by MioQuispe** [comment]
> When use [useConnect]
> 
> ![image](https://user-images.githubusercontent.com/17244631/171182799-9336333b-97e2-41ce-b9a9-e5e82ec09678.png)

Hey thanks for reporting. Can you tell me a bit more like which versions you are using, and if its svelte/vue/react?
some code could be good too

**Comment by MioQuispe** [comment]
Ok I will probably investigate it during the week. thanks for reporting

**Comment by tarek-eg** [comment]
I saw the same issue too with react and latest version

**Comment by MioQuispe** [comment]
> When use [useConnect]
> 
> ![image](https://user-images.githubusercontent.com/17244631/171182799-9336333b-97e2-41ce-b9a9-e5e82ec09678.png)

Hey please try latest version 0.1.0 and see if you're still getting it. I havent encountered it myself.
