### ISSUE TITLE
want to get bolck heigh  when use useTransfer()?

### ISSUE THREAD

**Issue by uncleEli** [Connect2IC/connect2ic#13]
in my project,we need to get the bolck height when the transaction completed.
but useTransfer[0]() return nothing when I see zhe sourcecode in @connect2ic/react/dist/connect2ic-react.cjs.dev.js(line 307)

**Comment by MioQuispe** [comment]
> in my project,we need to get the bolck height when the transaction completed. but useTransfer0 return nothing when I see zhe sourcecode in @connect2ic/react/dist/connect2ic-react.cjs.dev.js(line 307)

Hey, yes that would be good to have. I will see what I can do. I think there was some inconsistency in how the wallets handled it, but I will take another look at it.

**Comment by MioQuispe** [comment]
> in my project,we need to get the bolck height when the transaction completed. but useTransfer0 return nothing when I see zhe sourcecode in @connect2ic/react/dist/connect2ic-react.cjs.dev.js(line 307)

Try latest version 0.1.0
The blockheight is returned now.
