### ISSUE TITLE
Upgrade @dfinity/* Package Version

### ISSUE THREAD

**Issue by Mulander-J** [Connect2IC/connect2ic#14]
@dfinity/agent-js current version [v0.11.2](https://github.com/dfinity/agent-js/releases/tag/v0.11.2)
in this repo v0.10.4

**Comment by MioQuispe** [comment]
> @dfinity/agent-js current version [v0.11.2](https://github.com/dfinity/agent-js/releases/tag/v0.11.2) in this repo v0.10.4

Ah yes I will fix that soon. Thanks for reporting.

**Comment by MioQuispe** [comment]
> @dfinity/agent-js current version [v0.11.2](https://github.com/dfinity/agent-js/releases/tag/v0.11.2) in this repo v0.10.4

Should be fixed now. Try latest version 0.1.0
