### ISSUE TITLE
please consider adding a pure JavaScript example :)

### ISSUE THREAD

**Issue by AVOlight** [Connect2IC/connect2ic#15]
Hi, Thank you very much for this :D
please consider adding a pure JavaScript example :)

**Comment by neeboo** [comment]
Hi @AVOlight , would you elaborate the scenario that needs a pure JavaScript example?  Is the typescript example not working or you need some specific execution environment?

**Comment by AVOlight** [comment]
Hi @neeboo, sorry yes I'm not very experienced with web so pure JavaScript is the easiest way for me to connect through a JavaScript Unity plugin.

**Comment by MioQuispe** [comment]
> Hi @neeboo, sorry yes I'm not very experienced with web so pure JavaScript is the easiest way for me to connect through a JavaScript Unity plugin.

Hey, I will be exposing the client so it can be used outside the supported frameworks yes.

**Comment by MioQuispe** [comment]
> Hi @neeboo, sorry yes I'm not very experienced with web so pure JavaScript is the easiest way for me to connect through a JavaScript Unity plugin.

Hey! Please try the latest version 0.1.0
The client is exposed now. See here: https://connect2ic.github.io/docs/docs/Core/Client

It may not be perfect but hopefully we can fix and improve it according to your needs.

**Comment by AVOlight** [comment]
Thank you very much :)

**Comment by AVOlight** [comment]
Thank you very much :)
