### ISSUE TITLE
Issues trying react example

### ISSUE THREAD

**Issue by tarek-eg** [Connect2IC/connect2ic#17]
Hello,
When trying to run the react example I got some errors.
When installing the project I got:
```
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@connect2ic%2fcanisters - Not found
npm ERR! 404 
npm ERR! 404  '@connect2ic/canisters@*' is not in this registry.
```
The package `@connect2ic/fcanisters` is not published to npm, removing from package.json solved the issue since it is not a dependency.

when I run `dfx deploy` I got other issues

```
Error: Failed while trying to deploy canisters.
Caused by: Failed while trying to deploy canisters.
  Failed to build call canisters.
    Failed while trying to build all canisters.
      The post-build step failed for canister 'ryjl3-tyaaa-aaaaa-aaaba-cai' (assets) with an embedded error: Failed to build frontend for network 'local'.: The command '"npm" "run" "build"' failed with exit status 'exit status: 2'.
Stdout:

> new-create-ic-app-react@0.0.0 build
> tsc && vite build

frontend/components/Counter.tsx(14,14): error TS2345: Argument of type 'unknown' is not assignable to parameter of type 'SetStateAction<undefined>'.
frontend/components/Counter.tsx(31,48): error TS2339: Property 'toString' does not exist on type 'never'.
frontend/components/Profile.tsx(10,35): error TS2339: Property 'isWallet' does not exist on type '{ readonly principal: string | undefined; readonly activeProvider: { icon: any; connector: IConnector & Partial<IWalletConnector>; name: string; id: string; } | undefined; ... 5 more ...; readonly disconnect: () => void; }'.
frontend/components/Transfer.tsx(10,11): error TS2339: Property 'isWallet' does not exist on type '{ readonly principal: string | undefined; readonly activeProvider: { icon: any; connector: IConnector & Partial<IWalletConnector>; name: string; id: string; } | undefined; ... 5 more ...; readonly disconnect: () => void; }'.

Stderr:
```

Thanks

**Comment by MioQuispe** [comment]
> Hello, When trying to run the react example I got some errors. When installing the project I got:
> 
> ```
> npm ERR! 404 Not Found - GET https://registry.npmjs.org/@connect2ic%2fcanisters - Not found
> npm ERR! 404 
> npm ERR! 404  '@connect2ic/canisters@*' is not in this registry.
> ```
> 
> The package `@connect2ic/fcanisters` is not published to npm, removing from package.json solved the issue since it is not a dependency.
> 
> when I run `dfx deploy` I got other issues
> 
> ```
> Error: Failed while trying to deploy canisters.
> Caused by: Failed while trying to deploy canisters.
>   Failed to build call canisters.
>     Failed while trying to build all canisters.
>       The post-build step failed for canister 'ryjl3-tyaaa-aaaaa-aaaba-cai' (assets) with an embedded error: Failed to build frontend for network 'local'.: The command '"npm" "run" "build"' failed with exit status 'exit status: 2'.
> Stdout:
> 
> > new-create-ic-app-react@0.0.0 build
> > tsc && vite build
> 
> frontend/components/Counter.tsx(14,14): error TS2345: Argument of type 'unknown' is not assignable to parameter of type 'SetStateAction<undefined>'.
> frontend/components/Counter.tsx(31,48): error TS2339: Property 'toString' does not exist on type 'never'.
> frontend/components/Profile.tsx(10,35): error TS2339: Property 'isWallet' does not exist on type '{ readonly principal: string | undefined; readonly activeProvider: { icon: any; connector: IConnector & Partial<IWalletConnector>; name: string; id: string; } | undefined; ... 5 more ...; readonly disconnect: () => void; }'.
> frontend/components/Transfer.tsx(10,11): error TS2339: Property 'isWallet' does not exist on type '{ readonly principal: string | undefined; readonly activeProvider: { icon: any; connector: IConnector & Partial<IWalletConnector>; name: string; id: string; } | undefined; ... 5 more ...; readonly disconnect: () => void; }'.
> 
> Stderr:
> ```
> 
> Thanks

Hey it should be fixed now hopefully. Try latest version 0.1.0
