### ISSUE TITLE
useConnect in vue-router global guard

### ISSUE THREAD

**Issue by danielterwiel** [Connect2IC/connect2ic#21]
I need useConnect's `isConnected` value in vue-router's [global-router-guards](https://v3.router.vuejs.org/guide/advanced/navigation-guards.html#global-before-guards) to protect certain routes. But because useConnect calls vue's `inject` method before the context is initiated, this pattern fails.

My gist of router.js:

```js
const c = useConnect()
router.beforeEach((to, _from, next) => {
  if (to.meta.requiresAuth && c.isConnected.value) {
...
```

![CleanShot 2022-07-06 at 16 06 39](https://user-images.githubusercontent.com/25886902/177571633-d9a8220d-82f7-46f7-baa3-b16aba741dbc.png)

It's a bit a chicken & egg problem. My previous custom implementation for these guards worked a bit differently. Do you have any suggestion on how to avoid this elegantly?

Hope the description is sufficient. Let me know if you need an entire reproduction repository to illustrate the issue.

-edit- since the issue is triggered upon destructuring, I suspect passing a defaultValue to the `inject` call would solve this issue, but I cannot foresee the impact of doing so

**Comment by MioQuispe** [comment]
> I need useConnect's `isConnected` value in vue-router's [global-router-guards](https://v3.router.vuejs.org/guide/advanced/navigation-guards.html#global-before-guards) to protect certain routes. But because useConnect calls vue's `inject` method before the context is initiated, this pattern fails.
> 
> My gist of router.js:
> 
> ```js
> const c = useConnect()
> router.beforeEach((to, _from, next) => {
>   if (to.meta.requiresAuth && c.isConnected.value) {
> ...
> ```
> 
> ![CleanShot 2022-07-06 at 16 06 39](https://user-images.githubusercontent.com/25886902/177571633-d9a8220d-82f7-46f7-baa3-b16aba741dbc.png)
> 
> It's a bit a chicken & egg problem. My previous custom implementation for these guards worked a bit differently. Do you have any suggestion on how to avoid this elegantly?
> 
> Hope the description is sufficient. Let me know if you need an entire reproduction repository to illustrate the issue.
> 
> -edit- since the issue is triggered upon destructuring, I suspect passing a defaultValue to the `inject` call would solve this issue, but I cannot foresee the impact of doing so

Hey in this case you should probably use the client instead.
Sometimes the composables/hooks indeed aren't enough, even when using a framework so you can do something like this:

import client from "./client.ts"; // instantiate the connect2ic client there

if (client.status === "connected") {

}
