### ISSUE TITLE
error when use defaultProviders

### ISSUE THREAD

**Issue by himyyy** [Connect2IC/connect2ic#7]
defaultProviders in version 0.0.7, if not installed infinity wallet, there happened this error:
<img width="665" alt="infinity" src="https://user-images.githubusercontent.com/13343279/169510705-2f77f253-b5e9-46b4-98cf-3982d443b852.png">

**Comment by MioQuispe** [comment]
Hey! Thanks for reporting. I will fix it soon.

**Comment by MioQuispe** [comment]
> defaultProviders in version 0.0.7, if not installed infinity wallet, there happened this error: <img alt="infinity" width="665" src="https://user-images.githubusercontent.com/13343279/169510705-2f77f253-b5e9-46b4-98cf-3982d443b852.png">

Should be fixed now in 0.1.0
Let me know if it works for you

**Comment by himyyy** [comment]
It's works now.
